#!/usr/bin/env bash
# Instal nginx on your web-01 server
# When querying Nginx at its root / with a GET request (requesting a page)
# Nginx should be listening on port 80
# using curl, it must return a page that contains the string Hello World!
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
